wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1635659623
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 2
      4: 3.7.11
      5: 0.12.5
      8:
      - 5
drop_rate_fcn:
  desc: null
  value: 3
drop_rate_ocr:
  desc: null
  value: 6
drop_rate_swin:
  desc: null
  value: 5
